<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RistoraNET</a>
        </div>
        <ul class="nav navbar-nav">
        <li><a href="#">HOME</a></li>
        </ul>
        <?php if(Session::get('autenticado')): ?>
          
          <ul class="nav navbar-nav pull-right">
            
            <li><a href="<?=BASE_URL?>login/cerrar" class="btn btn-danger"><span class="glyphicon glyphicon-fire"> </span> Salir</a></li>
            
          </ul>
       
          <div class="navbar-form pull-right">
              <strong style="color: white;">Bienvenido, <u><?php echo Session::get('nombre') ?></u></strong>
          </div>
        <?php endif; ?>  
      </div>
    </div>